apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      name: appport
      port: {{ .Values.service.appPort }}
      targetPort: {{ .Values.service.appPort }}
    - protocol: TCP
      name: metricport
      port: {{ .Values.service.metricPort }}
      targetPort: {{ .Values.service.metricPort }}
  type: NodePort