replicaCount: 3

image:
  repository: tamvlb/stroke-pred-api
  tag: latest
  pullPolicy: IfNotPresent

api:
  containerPort: 7000

service:
  type: NodePort
  port: 80
  targetPort: 7000

ingress:
  enabled: false