replicaCount: 3

image:
  repository: tamvlb/stroke_pred_api
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  appPort: 7000
  metricPort: 8001

env:
  - name: MLFLOW_TRACKING_URI
    value: http://192.168.100.61:5001
  - name: JAEGER_URI
    value: http://192.168.100.61:4318/v1/traces

ingress:
  enabled: false