version: '3.9'

services:
  fastapi_ml:
    build: .
    container_name: fastapi_mlflow
    ports:
      - "7000:7000"
    volumes:
      - ./app:/app
    environment:
      - MLFLOW_TRACKING_URI={MLFLOW_TRACKING_URI}
    extra_hosts:
      - "host.docker.internal:host-gateway"