version: '3.8'

services:
  api:
    build: .
    container_name: fastapi-stroke-api
    ports:
      - "7000:7000"
    depends_on:
      - jaeger
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://172.17.0.1:4318 
      - MLFLOW_TRACKING_URI={MLFLOW_TRACKING_URI}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"    # OTLP HTTP receiver
    command:
      - "--collector.otlp.enabled=true"
