version: '3.8'

services:
  api:
    build: .
    container_name: fastapi-stroke-api
    ports:
      - "7000:7000"
    depends_on:
      - jaeger:
        - condition: service_healthy
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "${JAEGER_URI}"
      MLFLOW_TRACKING_URI: "${MLFLOW_TRACKING_URI}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"    # OTLP HTTP receiver
    command:
      - "--collector.otlp.enabled=true"
    healthcheck:
      - test: ["CMD", "wget", "--spider", "-q", "http://localhost:16686"]
      - interval: 10s
      - timeout: 5s
      - retries: 5
