version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"    # OTLP HTTP receiver
    command:
      - "--collector.otlp.enabled=true"
      - "--collector.otlp.http.host-port=:4318"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:16686"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: fastapi-stroke-api
    ports:
      - "7000:7000"
    depends_on:
      - jaeger  # Only wait for container to start (not healthy)
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318/v1/traces
      - MLFLOW_TRACKING_URI=http://host.docker.internal:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"
