version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.54
    restart: unless-stopped
    container_name: jaeger
    ports:
      - "16686:16686" 
      - "14250:14250" 
      - "4318:4318"    
    command:
      - "--collector.otlp.enabled=true"
